### ISSUE TITLE
Travis tests all failing with connection refused

### ISSUE THREAD

**Issue by stuaxo** [kiddouk/redisco#51]
Will see if there is anything obvious:

```
======================================================================

ERROR: test_CharField (redisco.tests.BooleanFieldTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/kiddouk/redisco/redisco/models/basetests.py", line 26, in setUp

    self.client.flushdb()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/redis/client.py", line 652, in flushdb

    return self.execute_command('FLUSHDB')

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command

    connection.send_command(*args)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command

    self.send_packed_command(self.pack_command(*args))

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command

    self.connect()

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/redis/connection.py", line 442, in connect

    raise ConnectionError(self._error_message(e))

ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```

**Comment by stuaxo** [comment]
Pull request:  https://github.com/kiddouk/redisco/pull/52

**Comment by stuaxo** [comment]
Closing as pull request merged and tests now passing.
